apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      name: http
      port: 3100 
      targetPort: 3100
