version: '3'
services:
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./loki/data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    container_name: grafana
  clash-tracing:
    build: .
    environment:
      CLASH_HOST: 'host.docker.internal:9090'
      CLASH_TOKEN: ''
      LOKI_ADDR: 'http://loki:3100/loki/api/v1/push'
    container_name: clash-tracing
