apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: monitoring
  labels:
    app: vector
spec:
  selector:
    app: vector
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 9000
